### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Draky50110** [ginsterbusch/mastodon-embed#1]
Hi.

Your plugin seems attractive but it does not embed my Mastodon status.

In fact, it displays the tag/URL (plain text).

Maybe not compatible with another plugin ?

**Comment by ginsterbusch** [comment]
@Draky50110  What exactly did you do?
The only clash that may be possible with a plugin is: Having the original mastodon-embed installed. You'd have to disable it prior use.

Another issue that happens a lot with shortcodes: Putting shortcodes into shortcodes. WP doesnt like that .. much, ie. doesnt really support it. A fix, depending on the situation, is to just add another do_shortcode( 'xyz' ... ) filter around the **OUTER** shortcode action. 

... Yes, I realize thats not very easy to apply for the regular user.

Could you provide a list of your installed plugins (and include the theme, if its a premium one)?
One of the plugins to accomplish this: https://wordpress.org/plugins/list-plugins/

**Comment by Draky50110** [comment]
I just tested it on a test instance of WP : https://www.draky.net/wordpress/2017/04/22/mastodon/

I don't have any plugin on this WordPress, express this Mastodon one.
As you can see, it is NOT embeded :/

**Comment by ginsterbusch** [comment]
@Draky50110  ok, found the issue: You only have to use `mastodon_embed` as shortcode tag IF the other plugin is enabled, too. Else, just use `[mastodon]url[/mastodon]` ;)

Also, the documentation states something else, thus I'm correcting this in the documentation right now ;)

**Comment by Draky50110** [comment]
Thanks.
Got another problem now : as my blog is full forced to SSL, Firefox or Chromium block the display (Firefox have an error message about security strategy) :/

Not sure this is related to your plugin.

Anyway thanks and think about publish it on WP repository ;)

**Comment by ginsterbusch** [comment]
That was my first thought when reading the source code of original mastodon embed - "iframe? but with SSL origin and CORS, this totally might explode ...?!"

Which is why I implemented the "direct embed" method. You enable it with setting the **disable_iframe** attribute to **1** in the shortcode tag:

`[mastodon disable_iframe="1"]my-url[/mastodon]`

This should load the data inside the plugin, parse and output it directly as normal HTML - see example on the following test page: http://testdrive.usability-idealist.de/mastodon-embed-test/

cu, w0lf.

**Comment by Draky50110** [comment]
Not working even with the disable_iframe="1" param.

Debug mode in source code of the page...

I just use this : `[mastodon disable_iframe="1"]https://mastodon.network/@ParigotManchot/1964928[/mastodon]`

**Comment by ginsterbusch** [comment]
Guh, I should stay with decisions. Just saw I removed the "disable_iframe" attribute a while ago and replaced it with "no_iframe". Still doesnt solve the issue - out of some unknown reason, instead of loading the SSL resource, its loading with unencrypted "http" (see above mentioned test page). 

Gonna dig further into this. Lets get this thing working! ;)

cu, w0lf.

**Comment by Draky50110** [comment]
Ok.
I can see the embed in your test page ;)
Will replace with no_iframe="1".

Ok, no_iframe="1" displays it correctly on my test page :D 
Thanks a lot :)
