### ISSUE TITLE
About "Show more" link 

### ISSUE THREAD

**Issue by itsumonotakumi** [ginsterbusch/mastodon-embed#4]
Do you know Mastodon's CW or NSFW?
I try to display their toot on my blog by this plugin, and I know "Show more" link's behavior is strange.
This is sample toot below:

[mastodon height="100"]https://pawoo.net/@itsumonotakumi/2234411[/mastodon]

After I clicked the link, my browser moved page top area.
Is this correct behavior of this plugin?

**Comment by ginsterbusch** [comment]
The "hide / display" button inside the iframe is linking to '#', so that is not part of the plugin, but correct behaviour of the browser. More or less so, though.

Normal behaviour of the browser should be: Do nothing. Because its not on the same domain. So your browser might be broken - or there is some extension installed that interferes with normal behaviour. Or maybe you did change a configuration setting, eg. about the same-domain policy.

What browser (version) are you using and on what platform, (mobile, desktop, etc.)? And are you using any kind of extensions / add-ons with that? if yes, please list them.

cu, w0lf.

**Comment by ginsterbusch** [comment]
Hm .. tested in Firefox and Chrome: No "jump to top" behaviour so far.

**Comment by itsumonotakumi** [comment]
Thank you for your quick check!

I knew my case correctly. I used it with being enabling "no_iframe" option.
When I didn't use "no_iframe" option of the tag, my browser did nothing.

Whether this option is enabled or disabled, I think the "hide / display" button should be linking to original toot page or displaying all toot data. 
Is it difficult? Is it incorrect?

**Comment by itsumonotakumi** [comment]
By the way, the target page is here.
https://takulog.info/mastodon-embed-wordpress-plugin/#foldingtoot

**Comment by ginsterbusch** [comment]
Sadly, the original content doesnt link to it directly, which is rather user-unfriendly. Though I've built a small JS yesterday, which should solve this, unhiding the CW / NSFW content (it's also there, just set to display: none).

**Comment by itsumonotakumi** [comment]
OK, I understood it. But I think that it is not necessarily to link to unhiding CW/NFSW content but  to link to hiding CW/NFSW content as well. I think that the behavior of current version is regrettable..

**Comment by ginsterbusch** [comment]
It's going to work similar to the original web application (Mastodon instance), ie. when you click on the "read more" link, it'll open the hidden content.

It's already linking to the original toot, so what would be the purpose of adding an additional link?

**Comment by itsumonotakumi** [comment]
Sorry for my late reply!
I think that the linking to the original toot is better than current specification of it.
In any case, the user is lost in the current specifications.

**Comment by ginsterbusch** [comment]
the current specifications of the CW / NSFW format of Mastodon?
possibly. they (ie. the masto devs) are currently lamenting about replacing this Content Warning / NSFW label with something else, which is more refined, including a different icon, because its not always about NSFW (and who decides that anyway?).

I might be adding some kind of picture / icon thingy to the direct embed "read more" link, too. or maybe. just for clarifying the feature a bit. Maybe add some title tag (displays as tooltip in desktop browsers) as well.

cu, w0lf.

**Comment by itsumonotakumi** [comment]
Sorry for my bad English..

"Current specification" of my comment is "Mastodon Embed" plugin's.
Some web site visitors get lost reading operation by its behavior linking to nothing or page top.

**Comment by ginsterbusch** [comment]
Once again: this is NOT the plugin behaviour. The '#' "linking" to the top is all done by the browser, and YES, that is the OFFICIAL W3C recommendation.

BTT: Having not embedded any toots with CW / NSFW before, of corpse the content is currently not being displayed when clicking the "read more"-link (which sadly links to '#' instead something more useful, leading to the current behaviour; which again is NOT my doing, but apparently the default setup of the web app / web mastodon instance). Ie. me not being aware of that ^_^

So in the very next release, there will be a JS helper included, which will show / hide the hidden content when clicking on the "read more"-link. Hope that clarifies the circumstances.

Its just that I'm quite busy with work right now, so no release (yet). But hopefully am going to find some time today or tomorrow :)

cu, w0lf.
